export const PRODUCT_REQUEST_LIST = "PRODUCT_REQUEST_LIST";
export const PRODUCT_SUCCESS_LIST = "PRODUCT_SUCCESS_LIST";
export const PRODUCT_FAIL_LIST = "PRODUCT_FAIL_LIST";


export const PRODUCT_REQUEST_DETAILS = "PRODUCT_REQUEST_DETAILS";
export const PRODUCT_SUCCESS_DETAILS = "PRODUCT_SUCCESS_DETAILS";
export const PRODUCT_FAIL_DETAILS = "PRODUCT_FAIL_DETAILS";